apiVersion: v1
kind: PersistentVolume
metadata:
  name: h2-persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/h2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: h2-persistent-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
